// public/src/components/Toast/Toast.vue
<script setup>
import { useToast } from './useToast'
const { toasts } = useToast()
</script>

<template>
  <div class="fixed top-4 right-4 space-y-2 z-50">
    <div
      v-for="toast in toasts"
      :key="toast.id"
      class="px-4 py-2 rounded shadow-lg text-white"
      :class="{
        'bg-green-500': toast.type === 'success',
        'bg-red-500': toast.type === 'error',
        'bg-blue-500': toast.type === 'info',
        'animate-fade-in': toast.show,
        'animate-fade-out': !toast.show,
      }"
    >
      {{ toast.message }}
    </div>
  </div>
</template>

// publicA/src/app/shared/toast/toast.component.ts
import { Component, inject } from '@angular/core';
import { ToastService } from '../toast.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-toast',
  imports: [CommonModule],
  standalone: true,
  templateUrl: './toast.component.html',
  styleUrl: './toast.component.css',
})
export class ToastComponent {
  public toastService = inject(ToastService);
}

<div class="fixed top-4 right-4 flex flex-col gap-3 z-[9999]">
  @for (toast of toastService.toast$ | async; track toast.id) {
    <div
      (click)="toastService.remove(toast.id)"
      class="px-4 py-3 rounded-xl shadow-lg text-white cursor-pointer transition-all duration-300 ease-in-out transform hover:scale-105"
      [ngClass]="{
        'bg-green-500': toast.type === 'success',
        'bg-red-500': toast.type === 'error',
        'bg-blue-500': toast.type === 'info',
        'bg-yellow-500 text-black': toast.type === 'warning',
        'animate-slide-in-from-right': !toast.removing,
        'animate-bounce-in': !toast.removing,
        'animate-fade-out': toast.removing,
        'opacity-0 translate-x-full': toast.removing,
      }"
    >
      {{ toast.message }}
    </div>
  }
</div>
